[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc = "0.8.20"
ffi = true


# Default overrides for the CI runs.
[profile.ci]
force = true                                                     
verbosity = 4                                                    
fuzz = { runs = 10_000, max_test_rejects = 350_000 }             
invariant = { runs = 375, depth = 500 } 
